In [17]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [26]:
# Create a sample dataset
X = np.arange(30).reshape((10, 3))  # Features (10 observations, 3 features)
y = range(10)  # Target variable (labels)

In [28]:
# Initialize a Linear Regression model
model_one = LinearRegression(fit_intercept=False)  # No intercept term

In [30]:
# Normalize the data
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [32]:
# Split the data into training and test sets (60% training, 40% testing)
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.4, random_state = 42)

In [34]:
# Train the model on the training data
model_one.fit(X_train, y_train)

LinearRegression(fit_intercept=False)

In [38]:
# Make predictions on the test data
predictions = model_one.predict(X_test)

In [40]:
# Print the results
print("Training data (features):")
print(x_train)
print("Test data (features):")
print(x_test)
print("Test data (target variable):")
print(y_test)
print("Model predictions on test data:")
print(predictions)

Training data (features):
[[ 3  4  5]
 [21 22 23]
 [27 28 29]
 [ 9 10 11]
 [ 0  1  2]
 [18 19 20]]
Test data (features):
[[ 6  7  8]
 [24 25 26]
 [15 16 17]
 [12 13 14]]
Test data (target variable):
[8, 1, 5, 0]
Model predictions on test data:
[ 5.18 -5.18  0.74 -6.66]
